### ISSUE TITLE
无法爬取收藏夹的作品

### ISSUE THREAD

**Issue by Surtryyds** [justorez/pica-cli#3]
[logs_23146832291.zip](https://github.com/justorez/pica-cli/files/15111307/logs_23146832291.zip)
![image](https://github.com/justorez/pica-cli/assets/93626005/c85d1ce2-1db4-4bd3-99d4-db4d596b1dd6)
排行榜能够正常读取，这个响应400不知道是咋回事啊。

**Comment by justorez** [comment]
请核对自己的账号密码是否配置正确

**Comment by Surtryyds** [comment]
好的，感谢。

**Comment by Surtryyds** [comment]
我刚刚试了一下登录有问题应该是这样的：
![image](https://github.com/justorez/pica-cli/assets/93626005/489c5ab0-b351-49c6-85a6-066eab911d4d)
但是我的情况是400，应该不是账号密码问题。

**Comment by justorez** [comment]
勾选上调试模式，然后再发一下日志

**Comment by Surtryyds** [comment]
[logs_23169388240.zip](https://github.com/justorez/pica-cli/files/15124756/logs_23169388240.zip)
![image](https://github.com/justorez/pica-cli/assets/93626005/fcc6ac93-bcc8-43ab-b209-1947257b6c56)

**Comment by Surtryyds** [comment]
是不是因为有些收藏的作品后来被禁了，但是pic不能删除这些作品导致的

**Comment by justorez** [comment]
> 是不是因为有些收藏的作品后来被禁了，但是pic不能删除这些作品导致的

@Surtryyds 目测是的，直接在网站上也访问不到，你看看是哪些被网站删了，取消收藏再去下载。后续有时间，我会优化一下，把未找到的漫画跳过

**Comment by Surtryyds** [comment]
pic应该是有些bug，取消不了这些收藏的内容，有些收藏也是莫名其妙出现在收藏夹，删不掉。

**Comment by justorez** [comment]
@Surtryyds 那你可以先用着搜索功能去下载，毕竟下载收藏夹，如果内容特别多也容易失败。后续我会优化，只是这几天比较忙

**Comment by Surtryyds** [comment]
好的，谢谢佬
