### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by LinEndsa** [justorez/pica-cli#7]
请问在download下显示
Run pnpm start

> pica-cli@1.5.3 start /home/runner/work/pica-cli/pica-cli

> pica-cli@1.5.3 开始 /home/runner/work/pica-cli/pica-cli
> node dist/index.js

? 请输入账户密码
25h

25小时
✘ User force closed the prompt with 0 null

✘ 用户强制关闭提示符，为 0 null

并且在Compress下显示
Run pnpm start:zip

> pica-cli@1.5.3 start:zip /home/runner/work/pica-cli/pica-cli
> node dist/zip.js

⚠ 没有发现已下载的漫画

该怎么解决呢？

**Comment by justorez** [comment]
请阅读readme.md，按照说明配置相关参数，包括：账号密码等
